import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import { Toaster } from 'react-hot-toast';
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { TotalUsageContext } from "./(context)/TotalUsageCredit";

const outfit = Outfit({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Content-Morpher",
  description: "Generated by Amlan",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
      <ClerkProvider
    appearance={{
        layout: {
          // Hides the orange "Development mode" strip
          unsafe_disableDevelopmentModeWarnings: true,
        },
      }}
    >
      <html lang="en" >
      <body
      className={`${outfit.className} dark dark:bg-zinc-950 dark:text-white`}
      >
        <Toaster
        position="top-center"
        reverseOrder={false}
        />
        {children}
      </body>
    </html>
    </ClerkProvider>
    
    
    
  );
}
